[package]
name = "rust-infotheory"
version = "0.1.0"
authors = ["godzilla-but-nicer <patgwall@iu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
